<a href="https://colab.research.google.com/github/Dharshansk16/Deep-Learning-with-Pytorch/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
print("Hello World")

Hello World


In [68]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [69]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [70]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
scalar.ndim #scalar has no dimension

0

In [72]:
# Get Tensor back as Python int
scalar.item()

7

In [73]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [74]:
vector.ndim

1

In [75]:
vector.shape

torch.Size([2])

In [76]:
# Matrix

mat = torch.tensor([[1,2,3], [3,3,1], [5,6,7]])
mat

tensor([[1, 2, 3],
        [3, 3, 1],
        [5, 6, 7]])

In [77]:
mat.ndim

2

In [78]:
mat[1]

tensor([3, 3, 1])

In [79]:
mat[2]

tensor([5, 6, 7])

In [80]:
mat.shape

torch.Size([3, 3])

In [81]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [9,9,3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 9, 3]]])

In [82]:
TENSOR.ndim

3

In [83]:
TENSOR.shape

torch.Size([1, 3, 3])

In [84]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [9, 9, 3]])

In [85]:
TENSOR[0][1][1]

tensor(5)

### Random tensors

Why Random tensors?

Random tensors are important because the way many neural network learn is that they start with random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers->loop`

In [86]:
### create a random tensor of size (3, 4)
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.6289, 0.3902, 0.0193, 0.7181],
        [0.7603, 0.5081, 0.2206, 0.0952],
        [0.0834, 0.0108, 0.6821, 0.5568],
        [0.3784, 0.1952, 0.3899, 0.2028]])

In [87]:
random_tensor.ndim

2

In [88]:
random_tensor.shape

torch.Size([4, 4])

In [89]:
## create a random tensor wirth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [90]:
### Create Tensor of all zeros

zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [91]:
### create tensor of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [93]:
ones.dtype

torch.float32

### Creating a range of tensors

In [94]:
## use torch.arange()
torch.arange(0,19, 4)

tensor([ 0,  4,  8, 12, 16])

In [95]:
### Creating tensors like
one_to_ten = torch.arange(1,11)
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note: ** Tensor datatypes is one of the 3 big errors with pytorch and deep learning
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right device

In [96]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device your tensor on (gpu, cpu)
                               requires_grad=False) # whether or not track gradients with the tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [97]:
float_32_tensor.dtype #default datatype for tensor is float32

torch.float32

In [98]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [99]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device-to get device from a tensor, we can use `tensor.device`

In [100]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9929, 0.8920, 0.2996, 0.7846],
        [0.9508, 0.4926, 0.5622, 0.6250],
        [0.1261, 0.8648, 0.6834, 0.5708]])

In [101]:
#Find details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9929, 0.8920, 0.2996, 0.7846],
        [0.9508, 0.4926, 0.5622, 0.6250],
        [0.1261, 0.8648, 0.6834, 0.5708]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor Operations)

Tensor Operations include:
* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplication


In [102]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [103]:
#  multiply by 10 element wise
tensor = torch.tensor([1,2,3])
tensor*10

tensor([10, 20, 30])

In [104]:
#Substract 1 from the tensor
tensor-1

tensor([0, 1, 2])

In [105]:
# Try out pytorch in-built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


In [106]:
#Divide
tensor/2

tensor([0.5000, 1.0000, 1.5000])

## Matrix multiplication
# Two ways to perform matrix multiplication
  1.Element wise multiplication
  2.Matrix Multiplication(dot product)


In [107]:
#Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [108]:
#Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [109]:
### One Of the common errosrs in deep learning is shape errors
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2393, 0.7956],
        [0.9181, 0.6749]])

In [110]:
# Shapes for matrix multiplication


In [111]:
#To fix our tensor shape Issue , we can manipulate the shape of one of our tensors using transpose
tensor_A= torch.tensor([[1,3],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[4,5],
                         [8,9],
                         [6,5]])
torch.matmul(tensor_A,tensor_B.T)

tensor([[19, 35, 21],
        [32, 60, 38],
        [50, 94, 60]])

In [112]:
## Finding the min,max,mean,sum etc(tensor aggregation)

x= torch.arange(10, 100, 10)
print(torch.min(x))
print(torch.max(x))

tensor(10)
tensor(90)


In [113]:
## torch.mean() requires a tensor of float32 datatype to work
x.dtype
x=x.type(torch.float32)
torch.mean(x)

tensor(50.)

In [114]:
torch.sum(x)

tensor(450.)

## Indexing (selecting data from tensors)

In [115]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [116]:
## Index on tensor
x[0][0][1], x[0] , x[0][0]

(tensor(2),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]))

In [117]:
x[:,0] #You can use : to select all of a target dimension

tensor([[1, 2, 3]])

In [118]:
x[:,1]

tensor([[4, 5, 6]])

In [119]:
x =torch.arange(1,28).reshape(3, 3, 3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [120]:
x[:,0]

tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])

In [121]:
# To get all values of 0th dimension and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]])

In [122]:
x[:,:,:] #Get all values

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [123]:
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensors and Numpy

In [126]:
# Numpy array to tensor
import numpy as np

array=np.arange(1.0, 8.0)
tensor =torch.from_numpy(array).type(torch.float32) # numpy default dtype is float64 is reflected in tensor. tensor by default is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [127]:
#change the value of array
array = array+1
tensor , array #When value of array is changed tensor is not changed

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [130]:
tensor=torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [132]:
## Change the tensor
tensor = torch.arange(1,10)
numpy_array = tensor.numpy()
tensor = tensor+1
numpy_array , tensor #numpy array remains unchanged tensor and numpy_array are independent

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [134]:
## Reproducibility (trying to take random out of random)
torch.rand(3,3)
#To reduce randomness we can use **random seed**


tensor([[7.9858e-01, 3.0553e-04, 8.8798e-01],
        [7.9911e-01, 2.8753e-01, 8.8693e-01],
        [6.0089e-01, 1.0632e-01, 8.4938e-01]])

In [136]:
#Create two random tensors
random_tensor_A =torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A , random_tensor_B

(tensor([[0.4061, 0.3790, 0.2766, 0.0772],
         [0.0866, 0.5347, 0.6307, 0.9910],
         [0.3569, 0.7190, 0.1429, 0.3797]]),
 tensor([[0.4654, 0.6087, 0.8057, 0.2069],
         [0.1591, 0.8470, 0.9157, 0.1541],
         [0.5982, 0.3200, 0.3750, 0.2704]]))

In [138]:
#Random reproducible tensors

#set the random seed
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d =torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
