<a href="https://colab.research.google.com/github/Dharshansk16/Deep-Learning-with-Pytorch/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
print("Hello World")

Hello World


In [47]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [48]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [49]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [50]:
scalar.ndim #scalar has no dimension

0

In [51]:
# Get Tensor back as Python int
scalar.item()

7

In [52]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [53]:
vector.ndim

1

In [54]:
vector.shape

torch.Size([2])

In [55]:
# Matrix

mat = torch.tensor([[1,2,3], [3,3,1], [5,6,7]])
mat

tensor([[1, 2, 3],
        [3, 3, 1],
        [5, 6, 7]])

In [56]:
mat.ndim

2

In [57]:
mat[1]

tensor([3, 3, 1])

In [58]:
mat[2]

tensor([5, 6, 7])

In [59]:
mat.shape

torch.Size([3, 3])

In [60]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [9,9,3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 9, 3]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [9, 9, 3]])

In [64]:
TENSOR[0][1][1]

tensor(5)

### Random tensors

Why Random tensors?

Random tensors are important because the way many neural network learn is that they start with random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers->loop`

In [65]:
### create a random tensor of size (3, 4)
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.6658, 0.5540, 0.3454, 0.1300],
        [0.6841, 0.0867, 0.4424, 0.2560],
        [0.5382, 0.9571, 0.5909, 0.5303],
        [0.4577, 0.1926, 0.8775, 0.5327]])

In [66]:
random_tensor.ndim

2

In [67]:
random_tensor.shape

torch.Size([4, 4])

In [68]:
## create a random tensor wirth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [69]:
### Create Tensor of all zeros

zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
### create tensor of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
ones.dtype

torch.float32

### Creating a range of tensors

In [73]:
## use torch.arange()
torch.arange(0,19, 4)

tensor([ 0,  4,  8, 12, 16])

In [74]:
### Creating tensors like
one_to_ten = torch.arange(1,11)
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note: ** Tensor datatypes is one of the 3 big errors with pytorch and deep learning
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right device

In [75]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device your tensor on (gpu, cpu)
                               requires_grad=False) # whether or not track gradients with the tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [76]:
float_32_tensor.dtype #default datatype for tensor is float32

torch.float32

In [77]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16