<a href="https://colab.research.google.com/github/Dharshansk16/Deep-Learning-with-Pytorch/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #scalar has no dimension

0

In [ ]:
# Get Tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

mat = torch.tensor([[1,2,3], [3,3,1], [5,6,7]])
mat

tensor([[1, 2, 3],
        [3, 3, 1],
        [5, 6, 7]])

In [ ]:
mat.ndim

2

In [ ]:
mat[1]

tensor([3, 3, 1])

In [ ]:
mat[2]

tensor([5, 6, 7])

In [ ]:
mat.shape

torch.Size([3, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [9,9,3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 9, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [9, 9, 3]])

In [ ]:
TENSOR[0][1][1]

tensor(5)

### Random tensors

Why Random tensors?

Random tensors are important because the way many neural network learn is that they start with random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers->loop`

In [ ]:
### create a random tensor of size (3, 4)
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.1395, 0.0708, 0.0228, 0.3174],
        [0.6325, 0.9268, 0.5220, 0.9289],
        [0.9785, 0.5292, 0.7928, 0.5316],
        [0.8771, 0.6738, 0.9078, 0.9213]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([4, 4])

In [ ]:
## create a random tensor wirth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Create Tensor of all zeros

zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
### create tensor of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors

In [ ]:
## use torch.arange()
torch.arange(0,19, 4)

tensor([ 0,  4,  8, 12, 16])

In [ ]:
### Creating tensors like
one_to_ten = torch.arange(1,11)
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note: ** Tensor datatypes is one of the 3 big errors with pytorch and deep learning
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right device

In [ ]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device your tensor on (gpu, cpu)
                               requires_grad=False) # whether or not track gradients with the tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #default datatype for tensor is float32

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device-to get device from a tensor, we can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7713, 0.8978, 0.0945, 0.3129],
        [0.7494, 0.2118, 0.8864, 0.0577],
        [0.8553, 0.4387, 0.3191, 0.0293]])

In [ ]:
#Find details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7713, 0.8978, 0.0945, 0.3129],
        [0.7494, 0.2118, 0.8864, 0.0577],
        [0.8553, 0.4387, 0.3191, 0.0293]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor Operations)

Tensor Operations include:
* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplication


In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#  multiply by 10 element wise
tensor = torch.tensor([1,2,3])
tensor*10

tensor([10, 20, 30])

In [ ]:
#Substract 1 from the tensor
tensor-1

tensor([0, 1, 2])

In [ ]:
# Try out pytorch in-built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


In [ ]:
#Divide
tensor/2

tensor([0.5000, 1.0000, 1.5000])

## Matrix multiplication
# Two ways to perform matrix multiplication
  1.Element wise multiplication
  2.Matrix Multiplication(dot product)


In [ ]:
#Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [ ]:
### One Of the common errosrs in deep learning is shape errors
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.6663, 0.2613],
        [0.9233, 0.8406]])

In [ ]:
# Shapes for matrix multiplication


In [ ]:
#To fix our tensor shape Issue , we can manipulate the shape of one of our tensors using transpose
tensor_A= torch.tensor([[1,3],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[4,5],
                         [8,9],
                         [6,5]])
torch.matmul(tensor_A,tensor_B.T)

tensor([[19, 35, 21],
        [32, 60, 38],
        [50, 94, 60]])

In [ ]:
## Finding the min,max,mean,sum etc(tensor aggregation)

x= torch.arange(10, 100, 10)
print(torch.min(x))
print(torch.max(x))

tensor(10)
tensor(90)


In [ ]:
## torch.mean() requires a tensor of float32 datatype to work
x.dtype
x=x.type(torch.float32)
torch.mean(x)

tensor(50.)

In [ ]:
torch.sum(x)

tensor(450.)